
import { Course, SemesterConfig } from "../types";

const DAY_MAP: Record<string, string> = {
  'Monday': 'MO',
  'Tuesday': 'TU',
  'Wednesday': 'WE',
  'Thursday': 'TH',
  'Friday': 'FR',
  'Saturday': 'SA',
  'Sunday': 'SU'
};

const formatDateForICS = (dateStr: string, timeStr: string) => {
  // Combine YYYY-MM-DD and HH:mm into YYYYMMDDTHHMMSS
  const cleanDate = dateStr.replace(/-/g, '');
  const cleanTime = timeStr.replace(/:/g, '') + '00';
  return `${cleanDate}T${cleanTime}`;
};

const getFirstOccurrence = (startDate: string, dayName: string): string => {
  const targetDay = Object.keys(DAY_MAP).indexOf(dayName) + 1; // 1 (Mon) - 7 (Sun)
  const date = new Date(startDate);
  // getDay() is 0 (Sun) - 6 (Sat)
  // Our mapping assumes Monday is 1
  let currentDay = date.getDay();
  if (currentDay === 0) currentDay = 7;

  let diff = targetDay - currentDay;
  if (diff < 0) diff += 7;
  
  date.setDate(date.getDate() + diff);
  return date.toISOString().split('T')[0];
};

export const generateICS = (courses: Course[], config: SemesterConfig): string => {
  let icsLines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Schedule2Cal//NONSGML v1.0//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH'
  ];

  const untilDate = config.endDate.replace(/-/g, '') + 'T235959Z';

  courses.forEach(course => {
    course.days.forEach(day => {
      const dayCode = DAY_MAP[day];
      if (!dayCode) return;

      const firstDate = getFirstOccurrence(config.startDate, day);
      const dtStart = formatDateForICS(firstDate, course.startTime);
      const dtEnd = formatDateForICS(firstDate, course.endTime);

      icsLines.push('BEGIN:VEVENT');
      icsLines.push(`SUMMARY:${course.name}`);
      icsLines.push(`DTSTART;TZID=UTC:${dtStart}`);
      icsLines.push(`DTEND;TZID=UTC:${dtEnd}`);
      icsLines.push(`RRULE:FREQ=WEEKLY;BYDAY=${dayCode};UNTIL=${untilDate}`);
      if (course.location) {
        icsLines.push(`LOCATION:${course.location}`);
      }
      icsLines.push(`DESCRIPTION:Generated by Schedule2Cal`);
      icsLines.push('END:VEVENT');
    });
  });

  icsLines.push('END:VCALENDAR');
  return icsLines.join('\r\n');
};

export const downloadICSFile = (content: string, filename: string) => {
  const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
